server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.druid.driver-class-name}
      url: ${sky.datasource.druid.url}
      username: ${sky.datasource.druid.username}
      password: ${sky.datasource.druid.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    # 用户端jwt配置
    user-secret-key: itheima
    user-ttl: 720000000
    user-token-name: authentication
  alioss: # 1. 填写你的 Bucket 所在地域（北京）
      endpoint: ${sky.alioss.endpoint}
      # 2. 粘贴刚才获取的 AccessKey ID
      access-key-id:  ${sky.alioss.accesss-key-id}
      # 3. 粘贴刚才获取的 AccessKey Secret
      access-key-secret:  ${sky.alioss.access-key-secret}
      # 4. 填写你的 Bucket 名称
      bucket-name:  ${sky.alioss.bucket-name}